---
title: "Code book Getting and Cleaning Data Course Project"
output: html_document
date: "2023-08-09"
---
This code book describes how data are obtained, the variables in the tidy data set and how this tidy data set is received.

## Background information about Tidy Data

This document shows the variables present in the tidy data set of the means. The subjects are the participants, numbers from 1 to 6. The activities are fully written in de data set, and are: walking, walking upstairs, walking downstairs, sitting, standing, layig). Each participant wore a smartphone (Samsung Galaxy SII) on the waist. Using this device the 3-axial acceleration and angular velocity were measured at a 50Hz rate.

The experiments have been video-recorded to label the data manually.

The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

## Original data sets
Original data was obtained from the internet:
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

- 'README.txt'

- 'features_info.txt': Shows information about the variables used on the feature vector.

- 'features.txt': List of all features.

- 'activity_labels.txt': Links the class labels with their activity name.

- 'train/X_train.txt': Training set.

- 'train/y_train.txt': Training labels.

- 'test/X_test.txt': Test set.

- 'test/y_test.txt': Test labels.


## The Variables in the Tidy Data

```{Tidy Data Mean}
- 'timebodyaccelerometer'
- 'timegravityaccelerometer'
- 'timebodygyroscope'
- 'timebodyaccelerometermagnitude'
- 'timegravityaccelerometermagnitude'
- 'timebodygyroscopemagnitude'
- 'frequencybodyaccelerometer'
- 'frequencybodygyroscope'
- 'frequencybodyaccelerometermagnitude'
- 'frequencybodygyroscopemagnitude'
```
Note 1: For each variable there is an X, Y, Z dimension in the database.
Note 2: For each variables there is a mean and standard deviation (std) variable.

## Data Manipulation
To receive the tidy data set, some manipulation steps were carried out:

1. Merges the training and the test sets to create one data set.

2. Extracts only the measurements on the mean and standard deviation for each measurement. 

3. Uses descriptive activity names to name the activities in the data set

4. Appropriately labels the data set with descriptive variable names. 

5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

The Tidy Data Set is saved as 'TidyDataMean.txt'